name = "discord-alerts"
main = "src/index.ts"
compatibility_date = "2022-10-12"

[triggers]
crons = [ "1 * * * *" ]

kv_namespaces = [
    { binding = "KV", id = "e41f2f32dae64d9099d7afa63784a345" }
]